### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Walkman100** [Walkman100/VBNCW#1]
Copied from vbncw.vb:
- [ ] scan current directory for .slns or .vbprojs, or skip if a valid file is provided as a flag
- [ ] output dir
- [ ] pre- and post-build tasks
- [ ] run pre-build tasks
- [ ] run VBNC, check & report errors
- [ ] run post-build tasks
- [ ] run output executable (if a flag is present?)
- [ ] first get configs set up, use "Release|AnyCPU" by default

Milestone stuff:
- [x] Successfully scan SLN
- [x] Successfully scan VBProj
- [ ] set up config variables, only load data from matching configs
- [ ] load scanned data into variables
- [ ] run compilers using variables
